### PR TITLE
Feature async

### PR DESCRIPTION
**Pull request by l3roken**
This change is [Reviewable](https://reviewable.io/reviews/casestack/cs-api-dotnet/9)

### CODE REVIEW

**Comment by arosequist** [comment]
Reviewed 11 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 63 \[r2\]](https://reviewable.io:443/reviews/casestack/cs-api-dotnet/9#-KDURXU0qNE9zpd2BaqT:-KDURXU0qNE9zpd2BaqU:493490876) ([raw file](https://github.com/casestack/cs-api-dotnet/blob/d459a8c8eba7eee817bb46122fc489151b7d814c/README.md#L63)):*
Should this be `GetCarrierAsync`?

---

*[cs-api-dotnet-tests/CaseStackAPITests.cs, line 121 \[r2\]](https://reviewable.io:443/reviews/casestack/cs-api-dotnet/9#-KDUSB0GQ_S88LM4vI9-:-KDUSB0GQ_S88LM4vI90:-714112367) ([raw file](https://github.com/casestack/cs-api-dotnet/blob/d459a8c8eba7eee817bb46122fc489151b7d814c/cs-api-dotnet-tests/CaseStackAPITests.cs#L121)):*
Should this line be deleted?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/casestack/cs-api-dotnet/9)*

**Comment by l3roken** [comment]
*[README.md, line 63 \[r2\]](https://reviewable.io:443/reviews/casestack/cs-api-dotnet/9#-KDURXU0qNE9zpd2BaqT:-KDUv-5k5WfBN0ud51Tq:1148798794) ([raw file](https://github.com/casestack/cs-api-dotnet/blob/d459a8c8eba7eee817bb46122fc489151b7d814c/README.md#L63)):*
Yes it should

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/casestack/cs-api-dotnet/9)*

**Comment by l3roken** [comment]
*[README.md, line 63 \[r2\]](https://reviewable.io:443/reviews/casestack/cs-api-dotnet/9#-KDURXU0qNE9zpd2BaqT:-KDUvavMYTEFcKcB7QYu:-921815110) ([raw file](https://github.com/casestack/cs-api-dotnet/blob/d459a8c8eba7eee817bb46122fc489151b7d814c/README.md#L63)):*
Corrected now

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/casestack/cs-api-dotnet/9)*

**Comment by l3roken** [comment]
*[cs-api-dotnet-tests/CaseStackAPITests.cs, line 121 \[r2\]](https://reviewable.io:443/reviews/casestack/cs-api-dotnet/9#-KDUSB0GQ_S88LM4vI9-:-KDV1kPvhJe2NCpGpK63:-672109411) ([raw file](https://github.com/casestack/cs-api-dotnet/blob/d459a8c8eba7eee817bb46122fc489151b7d814c/cs-api-dotnet-tests/CaseStackAPITests.cs#L121)):*
yes and fixed

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/casestack/cs-api-dotnet/9)*

**Comment by arosequist** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/casestack/cs-api-dotnet/9#-:-KDXzS2OzfiH5UzzGJ3W:1417088721)*

**Pull request merged**
